// Ensure trailing slash so axios builds correct URLs (baseURL + "api/..." => correct path)
export const BASE_URL = (import.meta.env.VITE_API_URL || "http://localhost:8000").replace(/\/?$/, "/");

// Log API base so you can verify in DevTools which backend you're hitting (localhost = local, other = deployed)
if (typeof window !== "undefined") {
  console.log("[API] BASE_URL:", BASE_URL);
}

export const API_PATHS = {
    BRANCHES: {
        GET_ALL: "api/branches",
        GET_DASHBOARD: "api/branches/dashboard",
        GET_BY_ID: (id) => `api/branches/${id}`,
        GET_EMPLOYEES: (id) => `api/branches/${id}/employees`,
        CREATE: "api/branches",
        UPDATE: (id) => `api/branches/${id}`,
        DELETE: (id) => `api/branches/${id}`,
    },
    AUTH: {
        REGISTER: "api/auth/register",
        PENDING_SIGNUP: "api/auth/pending-signup",
        LOGIN: "api/auth/login",
        LOGOUT: "api/auth/logout",
        FORGOT_PASSWORD: "api/auth/forgot-password",
        RESET_PASSWORD: "api/auth/reset-password",
        GET_PROFILE: "api/auth/me",
        UPDATE_PROFILE: "api/auth/me",
        PROFILE_PICTURE_UPLOAD: "api/auth/me/profile-picture",
        PROFILE_PICTURE: (filename) => `api/auth/profile-picture/${filename}`,
        TEAM: "api/auth/team",
        TEAM_MEMBER: (id) => `api/auth/team/${id}`,
        CLIENTS: "api/auth/clients",
        CLIENTS_DELETE: (id) => `api/auth/clients/${id}`,
    },
    SUBSCRIPTIONS: {
        ME: "api/subscriptions/me",
        INITIALIZE: "api/subscriptions/initialize",
        INITIALIZE_GUEST: "api/subscriptions/initialize-guest",
        CUSTOM: "api/subscriptions/custom",
    },
    INVOICES: {
        GET_ALL_INVOICES: "api/invoices",
        GET_INVOICE_BY_ID: (id) => `api/invoices/${id}`,
        UPDATE_INVOICE: (id) => `api/invoices/${id}`,
        DELETE_INVOICE: (id) => `api/invoices/${id}`,
        CONVERT_TO_INVOICE: (id) => `api/invoices/${id}/convert-to-invoice`,
    },
    MARKETING: {
        CAMPAIGNS: "api/marketing/campaigns",
        CAMPAIGN: (id) => `api/marketing/campaigns/${id}`,
        LANDING_PAGES: "api/marketing/landing-pages",
        LANDING_PAGE: (id) => `api/marketing/landing-pages/${id}`,
        WORKFLOWS: "api/marketing/workflows",
        WORKFLOW: (id) => `api/marketing/workflows/${id}`,
        LISTS: "api/marketing/lists",
        LIST: (id) => `api/marketing/lists/${id}`,
        FORMS: "api/marketing/forms",
        FORM: (id) => `api/marketing/forms/${id}`,
        FORM_PUBLIC: (id) => `api/marketing/forms/${id}/public`,
        FORM_SUBMIT: (id) => `api/marketing/forms/${id}/submit`,
        FORM_SUBMISSIONS: (id) => `api/marketing/forms/${id}/submissions`,
        TEMPLATES: "api/marketing/templates",
        TEMPLATE: (id) => `api/marketing/templates/${id}`,
        ANALYTICS: "api/marketing/analytics",
    },
    CRM: {
        CONTACTS: "api/crm/contacts",
        CONTACT: (id) => `api/crm/contacts/${id}`,
        COMPANIES: "api/crm/companies",
        COMPANY: (id) => `api/crm/companies/${id}`,
        LEADS: "api/crm/leads",
        LEAD: (id) => `api/crm/leads/${id}`,
        DEALS: "api/crm/deals",
        DEAL: (id) => `api/crm/deals/${id}`,
        ACTIVITIES: "api/crm/activities",
        ACTIVITY: (id) => `api/crm/activities/${id}`,
        REPORTS: "api/crm/reports",
    },
    ITEMS: {
        GET_ALL: "api/items",
        CREATE: "api/items",
        IMPORT: "api/items/import",
        UPDATE: (id) => `api/items/${id}`,
        DELETE: (id) => `api/items/${id}`,
        ADJUST_STOCK: (id) => `api/items/${id}/adjust-stock`,
        MOVEMENTS: (id) => `api/items/${id}/movements`,
        STOCK_MOVEMENTS: "api/items/stock/movements",
        STOCK_REPORT: "api/items/stock/report",
    },
    CATEGORIES: {
        GET_ALL: "api/categories",
        CREATE: "api/categories",
        UPDATE: (id) => `api/categories/${id}`,
        DELETE: (id) => `api/categories/${id}`,
    },
    SUPPLIERS: {
        GET_ALL: "api/suppliers",
        CREATE: "api/suppliers",
        UPDATE: (id) => `api/suppliers/${id}`,
        DELETE: (id) => `api/suppliers/${id}`,
    },
    EMPLOYEES: {
        GET_ALL: "api/employees",
        GET_ME: "api/employees/me",
        UPDATE_ME: "api/employees/me",
        WITHOUT_USER: "api/employees/without-user",
        CREATE: "api/employees",
        UPDATE: (id) => `api/employees/${id}`,
        DELETE: (id) => `api/employees/${id}`,
    },
    ATTENDANCE: {
        GET_ALL: "api/attendance",
        CREATE: "api/attendance",
        DELETE: (id) => `api/attendance/${id}`,
    },
    LEAVE_REQUESTS: {
        GET_ALL: "api/leave-requests",
        CREATE: "api/leave-requests",
        UPDATE: (id) => `api/leave-requests/${id}`,
        DELETE: (id) => `api/leave-requests/${id}`,
    },
    PAYROLL: {
        GET_ALL: "api/payroll",
        GET_ME: "api/payroll/me",
        CREATE: "api/payroll",
        UPDATE: (id) => `api/payroll/${id}`,
        DELETE: (id) => `api/payroll/${id}`,
    },
    SALARIES: {
        GET_ALL: "api/salaries",
        GET_ME: "api/salaries/me",
        CREATE: "api/salaries",
        DELETE: (id) => `api/salaries/${id}`,
    },
    HR_TASKS: {
        ONBOARDING: "api/hr-tasks/onboarding",
        ONBOARDING_BY_ID: (id) => `api/hr-tasks/onboarding/${id}`,
        OFFBOARDING: "api/hr-tasks/offboarding",
        OFFBOARDING_BY_ID: (id) => `api/hr-tasks/offboarding/${id}`,
    },
    HR_PERFORMANCE: {
        REVIEWS: "api/hr-performance/reviews",
        REVIEWS_BY_ID: (id) => `api/hr-performance/reviews/${id}`,
        GOALS: "api/hr-performance/goals",
        GOALS_BY_ID: (id) => `api/hr-performance/goals/${id}`,
    },
    HR_RECRUITMENT: {
        JOBS: "api/hr-recruitment/jobs",
        JOBS_BY_ID: (id) => `api/hr-recruitment/jobs/${id}`,
        APPLICATIONS: "api/hr-recruitment/applications",
        APPLICATIONS_BY_ID: (id) => `api/hr-recruitment/applications/${id}`,
    },
    MESSAGES: {
        CONTACTS: "api/messages/contacts",
        CONVERSATIONS: "api/messages/conversations",
        UNREAD_COUNT: "api/messages/unread-count",
        MESSAGES: "api/messages/messages",
        MESSAGE_BY_ID: (id) => `api/messages/messages/${id}`,
        SEND: "api/messages/messages",
        MARK_READ: "api/messages/messages/read",
        SET_REPLYING: "api/messages/replying",
        GET_REPLYING: "api/messages/replying",
        ATTACHMENT: (filename) => `api/messages/attachment/${filename}`,
        GROUPS: "api/messages/groups",
        CREATE_GROUP: "api/messages/groups",
    },
    AI: {
        PARSE_INVOICE_TEXT: "api/ai/parse-invoice",
        PARSE_INVOICE_IMAGE: "api/ai/parse-invoice-image",
        GENERATE_REMINDER: "api/ai/generate-reminder",
        GET_DASHBOARD_SUMMARY: "api/ai/dashboard-summary",
        GENERATE_POLICY: "api/ai/generate-policy",
    },
    GRA: {
        SUBMIT_INVOICE: "api/gra/submit-invoice",
        SUBMIT_VAT_RETURN: "api/gra/submit-vat-return",
    },
    ACCOUNTING: {
        ACCOUNTS: "api/accounting/accounts",
        ACCOUNT: (id) => `api/accounting/accounts/${id}`,
        JOURNAL_ENTRIES: "api/accounting/journal-entries",
        JOURNAL_ENTRY: (id) => `api/accounting/journal-entries/${id}`,
        JOURNAL_ENTRY_POST: (id) => `api/accounting/journal-entries/${id}/post`,
        REPORT_GL: "api/accounting/reports/general-ledger",
        REPORT_TRIAL_BALANCE: "api/accounting/reports/trial-balance",
        REPORT_PROFIT_LOSS: "api/accounting/reports/profit-loss",
        REPORT_BALANCE_SHEET: "api/accounting/reports/balance-sheet",
        EXPENDITURES: "api/accounting/expenditures",
        EXPENDITURE: (id) => `api/accounting/expenditures/${id}`,
        EXPENDITURE_RECORD_TO_LEDGER: (id) => `api/accounting/expenditures/${id}/record-to-ledger`,
        BILLS: "api/accounting/bills",
        BILL: (id) => `api/accounting/bills/${id}`,
        BUDGETS: "api/accounting/budgets",
        BUDGET: (id) => `api/accounting/budgets/${id}`,
        TAX_RULES: "api/accounting/tax-rules",
        TAX_RULE: (id) => `api/accounting/tax-rules/${id}`,
        EXCHANGE_RATES: "api/accounting/exchange-rates",
        EXCHANGE_RATE_EFFECTIVE: "api/accounting/exchange-rates/effective",
        EXCHANGE_RATE: (id) => `api/accounting/exchange-rates/${id}`,
    },
    DOCUMENTS: {
        LIST: "api/documents",
        UPLOAD: "api/documents",
        GET: (id) => `api/documents/${id}`,
        DELETE: (id) => `api/documents/${id}`,
    },
    PROJECTS: {
        LIST: "api/projects",
        GET: (id) => `api/projects/${id}`,
        CREATE: "api/projects",
        UPDATE: (id) => `api/projects/${id}`,
        DELETE: (id) => `api/projects/${id}`,
        TASKS: (projectId) => `api/projects/${projectId}/tasks`,
        TASK_UPDATE: (projectId, taskId) => `api/projects/${projectId}/tasks/${taskId}`,
        TASK_DELETE: (projectId, taskId) => `api/projects/${projectId}/tasks/${taskId}`,
        MILESTONES: (projectId) => `api/projects/${projectId}/milestones`,
        MILESTONE_UPDATE: (projectId, milestoneId) => `api/projects/${projectId}/milestones/${milestoneId}`,
        MILESTONE_DELETE: (projectId, milestoneId) => `api/projects/${projectId}/milestones/${milestoneId}`,
        TIME_ENTRIES: "api/projects/time-entries",
        TIME_ENTRY_UPDATE: (id) => `api/projects/time-entries/${id}`,
        TIME_ENTRY_DELETE: (id) => `api/projects/time-entries/${id}`,
    },
    PRODUCTION: {
        WORK_ORDERS: "api/production/work-orders",
        WORK_ORDER: (id) => `api/production/work-orders/${id}`,
        BOMS: "api/production/boms",
        BOM_BY_PARENT: (parentId) => `api/production/boms/by-parent/${parentId}`,
        BOM: (id) => `api/production/boms/${id}`,
        RESOURCES: "api/production/resources",
        RESOURCE: (id) => `api/production/resources/${id}`,
        CAPACITY: "api/production/capacity",
        ALLOCATIONS: "api/production/allocations",
        ALLOCATION: (id) => `api/production/allocations/${id}`,
        MAINTENANCE_SCHEDULES: "api/production/maintenance-schedules",
        MAINTENANCE_SCHEDULE: (id) => `api/production/maintenance-schedules/${id}`,
        MAINTENANCE_LOGS: "api/production/maintenance-logs",
    },
    SUPPLY_CHAIN: {
        SUPPLIERS: "api/supply-chain/suppliers",
        SUPPLIER: (id) => `api/supply-chain/suppliers/${id}`,
        WAREHOUSES: "api/supply-chain/warehouses",
        WAREHOUSE: (id) => `api/supply-chain/warehouses/${id}`,
        STOCK_LEVELS: "api/supply-chain/stock-levels",
        LOW_STOCK_ALERTS: "api/supply-chain/alerts/low-stock",
        PURCHASE_ORDERS: "api/supply-chain/purchase-orders",
        PURCHASE_ORDER: (id) => `api/supply-chain/purchase-orders/${id}`,
        PURCHASE_ORDER_RECEIVE: (id) => `api/supply-chain/purchase-orders/${id}/receive`,
        FORECASTS: "api/supply-chain/forecasts",
        FORECAST: (id) => `api/supply-chain/forecasts/${id}`,
    },
    INTEGRATIONS: {
        CONNECTED: "api/integrations/connected",
        AVAILABLE: "api/integrations/available",
        CONNECT: "api/integrations/connect",
        DISCONNECT: (id) => `api/integrations/${id}/disconnect`,
        API_KEYS: "api/integrations/api-keys",
        API_KEY_DELETE: (id) => `api/integrations/api-keys/${id}`,
        WEBHOOKS: "api/integrations/webhooks",
        WEBHOOK: (id) => `api/integrations/webhooks/${id}`,
    },
};